import { randomBackground } from "../utils/background";

const imageUrl =
    "https://cdna.artstation.com/p/assets/images/images/045/580/804/large/gonkdroid-monke-hd.jpg?1643064095";
export const users = [
    {
        id: 1,
        image: imageUrl,
        email: "user123@gmail.com",
        password: "user123",
        name: "Snow",
        age: 35,
        gender: "Male",
    },
    {
        id: 2,
        image: imageUrl,
        email: "user456@gmail.com",
        password: "user123",
        name: "Lannister Cersei",
        age: 42,
        gender: "Female",
    },
    {
        id: 3,
        image: imageUrl,
        email: "user1@gmail.com",
        password: "user123",
        name: "Lannister Jaime",
        age: 45,
        gender: "Male",
    },
    {
        id: 4,
        image: imageUrl,
        email: "user23@gmail.com",
        password: "user123",
        name: "Stark Arya",
        age: 16,
        gender: "Female",
    },
    {
        id: 5,
        image: imageUrl,
        email: "user13@gmail.com",
        password: "user123",
        name: "Targaryen Daenerys",
        age: null,
        gender: "Male",
    },
    {
        id: 6,
        image: imageUrl,
        email: "user143@gmail.com",
        password: "user123",
        name: "Melisandre",
        age: 150,
        gender: "Female",
    },
    {
        id: 7,
        image: imageUrl,
        email: "user163@gmail.com",
        password: "user123",
        name: "Clifford Ferrara",
        age: 44,
        gender: "Male",
    },
    {
        id: 8,
        image: imageUrl,
        email: "user133@gmail.com",
        password: "user123",
        name: "Frances Rossini",
        age: 36,
        gender: "Male",
    },
    {
        id: 9,
        image: imageUrl,
        email: "user16@gmail.com",
        password: "user123",
        name: "Roxie Harvey",
        age: 65,
        gender: "Female",
    },
    {
        id: 10,
        image: imageUrl,
        email: "user63@gmail.com",
        password: "user123",
        name: "Snow",
        age: 35,
        gender: "Male",
    },
    {
        id: 11,
        image: imageUrl,
        email: "user53@gmail.com",
        password: "user123",
        name: "Lannister Cersei",
        age: 42,
        gender: "Female",
    },
    {
        id: 12,
        image: imageUrl,
        email: "user126@gmail.com",
        password: "user123",
        name: "Lannister Jaime",
        age: 45,
        gender: "Male",
    },
    {
        id: 13,
        image: imageUrl,
        email: "user153@gmail.com",
        password: "user123",
        name: "Stark Arya",
        age: 16,
        gender: "Female",
    },
    {
        id: 14,
        image: imageUrl,
        email: "user127@gmail.com",
        password: "user123",
        name: "Targaryen Daenerys",
        age: null,
        gender: "Male",
    },
    {
        id: 15,
        image: imageUrl,
        email: "user177@gmail.com",
        password: "user123",
        name: "Melisandre",
        age: 150,
        gender: "Female",
    },
    {
        id: 16,
        image: imageUrl,
        email: "user343@gmail.com",
        password: "user123",
        name: "Clifford Ferrara",
        age: 44,
        gender: "Male",
    },
    {
        id: 17,
        image: imageUrl,
        email: "user323@gmail.com",
        password: "user123",
        name: "Frances Rossini",
        age: 36,
        gender: "Male",
    },
    {
        id: 18,
        image: imageUrl,
        email: "user453@gmail.com",
        password: "user123",
        name: "Roxie Harvey",
        age: 65,
        gender: "Female",
    },
];

export const admins = [
    {
        id: "1",
        name: "Admin",
        email: "admin123@gmail.com",
        password: "admin123",
    },
    {
        id: "2",
        name: "Admin2",
        email: "admin456@gmail.com",
        password: "admin123",
    },
];
